= Ⅲ year Ⅰ semester

== Subject list Ⅰ semester

- Программные средства САПР
- Разработка САПР
- Дискретная математика
- Методы обработки и анализа больших данных
- Физические основы проектирования электронно-компонентной базы
- ЭВМ и перифирийные устройства
- Твердотельная электроника
- Технология интегральных схем

== Программные средства САПР

- форма контроля: дифференцированный зачёт
.. оценка максимум: 20 баллов
- автомат: есть при условиях
.. Выполнить суперзадание первым за лабораторное занятие
.. Закрыть все лабораторные работы хотя бы на 7 баллов
.. Закрыть все СРС на лекциях хотя бы на 10 баллов в сумме

---

=== Лабораторные работы

- срок сдачи: неделя после даты занятия
- оценка максимум: 8 баллов
- оценка минимум: 6 баллов
- сдача вне срока: 5 балловэ
- количество: 8 лабораторных работ
. Реализация консольного варианта алгоритма Ли – алгоритма нахождения
кратчайшего пути на ДРП для трассировки межсоединений.
Анализ особенностей работы алгоритма.
.. дата: 4.09
.. сдачи по: 11.09
. Разработка программ с использованием Windows API. Общие вопросы:
создание окна, обработка событий. Пользовательские диалоги. Рисование
геометрических примитивов.
.. дата: 18.09
.. сдача не требуется
. Написание программ с использованием Windows API. Программа,
имитирующая схематик: рисование схемотехнических элементов,
перемещение схемотехнических элементов, отображение сетки. Расчёт
коэффициентов масштабирования для визуализации объектов, масштаб
которых не совпадает с логическим масштабом окна.
.. дата: 2.10
.. сдача до: 9.10
. Написание программ с использованием Windows API. Программа,
имитирующая графический постпроцессор: отображение результатов
моделирования, масштабирование графиков.
.. дата: 16.10
.. сдача до: 23.10
. Написание программ с использованием библиотеки OpenGL. Принципы
построения двумерной и трёхмерной графики. Обработка событий от
клавиатуры и мыши.
.. дата: 30.10
.. сдача не требуется
. Написание программ с использованием библиотеки OpenGL. Построение
трёхмерной поверхности по расчётным данным из файла.
.. дата: 14.11
.. сдача до: 21.11
. Написание программ с использованием библиотеки OpenGL.
Визуализация трёхмерных объектов на примере результатов
технологического моделирования Synopsys TCAD.
.. дата: 27.11
.. сдача до: 4.12
. Написание программ с использованием библиотеки OpenGL. Разработка
визуализатора расчётчика на примере совмещения кода нахождения
кратчайшего пути алгоритмом Ли и визуализации работы этого алгоритма.
.. дата: 11.12
.. сдача до: 18.12

---

=== СРС на лекциях

Первые 10 минут на лекциях 4, 6 и 8 в виде контрольных мероприятий.
- баллы за 1: 6
- баллы за 2: 5
- баллы за 3: 5 

== Методы обработки и анализа больших данных

== ЭВМ и перифирийные устройства

- форма контроля: зачёт
- рубежный контроль: 13 неделя
- консультации: каждый знаменатель в среду, 4204А кабинет, 15:30
.. даты: 9.09, 23.09, 7.10, 21.10, 4.11, 18.11, 2.12, 16.12
- выполненные задания необходимо заранее прислать на почту 
miehapmg@gmail.com? для согласования с преподавателем.

---

=== Контрольные работы

Вопросы контрольных работ полностью выложены.

. Контрольная работа на 12 неделе
. Контрольная работа на 14 неделе
. Контрольная работа на 16 неделе

---

=== Доклады 

Необходимо доложить информацию, защищать доклад от преподавателя, 
своё мнение не нужно. Можно читать с телефона.

. Перспективы развития микропроцессорной техники.
.. дата: 9.09
.. Требования к докладу:
- Состояние отрасли в данный момент. Какие микропроцессорные 
изделия производятся, в достаточном ли количестве.
- Оказывают ли влияние санкции?
- Пути преодоления санкций. Насколько успешно идёт преодоление?
- Ожидаемое состояние отрасли микроэлектроники через полгода, год, 
два года, пять лет и далее.
- Ожидаемое влияние состояния отрасли на экономику страны в целом 
(нет влияния; малое влияние выразится в том-то; влияние будет 
существенным в таких-то направлениях)
- Могут ли перспективы отрасли повлиять на ваши личные планы? Если 
да, то в каком направлении планы могут измениться?

. Опасности, связанные с цифровизацией.
- дата: 23.09
- Требования к докладу:

.. В докладе нужно дать список недемпфируемых опасностей связанных с 
цифровизацией, т.е. таких опасностей от которых пока нет нормальной 
защиты, т.е. такие опасности либо постоянно генерируют неприятности 
(но мы с ними миримся из-за общего положительного эффекта), либо могут 
в любой момент начать генерировать неприятности (а защиты пока нет).
Например, утечки персональных данных только возрастают и эту тенденцию 
пока невозможно переломить. Либо: все отечественные суперкомпьютеры 
сделаны на импортной базе, а если забугорщики заложили в свои 
процессоры бэкдоры и в какой-то момент, вырубят все наши суперкомпьютеры?
Писать об опасностях, которые нормально парируются, не надо. Например, 
не надо писать о том, что мошенники регулярно звонят «из СБ вашего 
банка» - достаточно перезвонить в банк и всё станет ясно.
.. Далее, для каждой недемпфируемой опасности нужно указать существует 
ли метод ее демпфирования, и если да, то почему он не применяется. 
Например, ваши передвижения по улице полностью отслеживаются городскими 
камерами. Если вы хотите, чтобы никто не знал, что вы посещаете 
любовницу (или подпольное казино), то придется существенно менять 
внешность (одежду и грим) и не брать с собой мобильник, но это 
большие хлопоты, поэтому большинство людей предпочитает не 
демпфировать эту опасность, а положиться на статистику и русский 
«Авось».

---

=== Эссе

Необходимо доложить информацию, и сформировать своё мнение. Можно читать
с телефона. Защита требуется.

. Организация импортозамещения в области производства ЭВМ и в области производства периферийных элементов в нашей стране.
.. дата: 7.10
.. Требования к эссе:
- Где сейчас в мире применяется импортозамещение и почему.
- Как в принципе можно организовать импортозамещение?
- Состояние импортозамешения в указанных областях в нашей стране.
- Какие действия предпринимаются правительством, частными фирмами и 
частными лицами для организации импортозамещения в указанных областях?
- Что из этого даст реальные результаты? Какие из результатов будут 
полезными, а какие не полезными?


. Какие глобальные изменения в мире произойдут, если удастся увеличить емкость батареи смартфона в 1000 раз?
.. дата: 21.10
.. Требования к эссе:
- Не нужно упоминать, что смартфон можно будет заряжать раз в год, 
либо вообще не заряжать, а просто купить через год новый. Это и так 
очевидно из формулировки задания.
- Нужно найти именно глобальные изменения, т.е. изменения, которые 
повлияют на жизнь большинства людей. Например, то что не нужно заряжать 
смартфон каждый день – это мелкое удобство пользователя. А изобретение 
жидких кристаллов позволило делать маленькие карманные экраны, что 
позволило иметь карманный компьютер, а затем и смартфон – это коснулось всех.
- Как показывает опыт, многие студенты находят лишь мелкие частные 
изменения, типа «охотники и туристы теперь всегда найдут дорогу домой 
по трекеру не боясь, что батарейка сядет», – это не глобальное 
изменение оно касается удобства небольшой совокупности людей.


---

=== ДЗ

Найти в интернете или придумать самому новое периферийное устройство.

- дата: до конца семестра

Требования к ДЗ:

- Устройство должно быть реально работающее, т.е. вам нужно 
обосновать то, что устройство может реально работать, что это не 
фантазия изобретателя.
- Требование «новое» не означает, что устройство сделано только в 
этом году, оно может быть предложено и в прошлые годы, но до сего 
дня мне его никто не показывал. В частности это значит, что если 
ваш одногруппник собирается принести описание того же самого 
устройства, то засчитано оно будет только тому, кто пришлет 
материалы первым, а второму придется искать что-то другое.
- Нужно только подробное описание устройства, а не принести его 
физически.
- Рекомендуется присылать сразу несколько устройств, потому что 
часто присылают либо то, что уже было, либо то, что не может быть 
реализовано, либо то, что не имеет практического смысла. Пример 
последнего это индукционная зарядка для грузовиков под поверхностью 
автомагистрали – это возможно сделать, но пустые потери энергии 
составят до 99% - смысла в этом нет.

== Твердотельная электроника

= Ⅲ year Ⅱ semester

== Subject list Ⅱ semester

- Автоматизация конструкторско-технологического проектирования
- Автоматизация функционально-логического проектирования
- Автоматизация схемотихнического проектирования
- Наноэлектроника
- Информационная безопасность
- Основы управления проектами
- Интегральная схемотехника
- Программирование. Программирование и проектирование миекропроцессорных систем

